name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
      with:
        node-version: 18.4.0
    - name: Install dependencies
      run: npm install
    - name: Create android app
      run: npm run build
    - name: Regenerate android app
      run: npm i @capacitor/android && rm -r android && npx cap add android

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
    - name: Build with Gradle
      run: cd android && ./gradlew build
      
